remove old python_pkgs directory. add boost_url base64

diff --git a/set_up_env b/set_up_env
--- a/set_up_env
+++ b/set_up_env
@@ -8,26 +8,29 @@ fail() {
     exit 1
 }
 
-# Check for dependencies.
+echo -n "Checking for dependencies..."
 which afl-showmap &>/dev/null || fail "Please install AFL++."
 which python3 &>/dev/null || fail "Please install python3."
+echo "done"
 
+echo -n "Setting up venv..."
 python3 -c 'import sys; exit(sys.prefix != sys.base_prefix)' || fail "Looks like you're already in a venv. This script needs to make its own venv. Please deactivate your venv and source this script again."
-
 rm -rf url_fuzz_env || fail "Couldn't remove old venv."
 python3 -m venv url_fuzz_env || fail "Couldn't make a venv."
-
 source ./url_fuzz_env/bin/activate || fail "Couldn't activate the venv."
-pip3 install --upgrade pip || { deactivate; fail "Couldn't update pip."; }
+pip3 install --upgrade pip &>/dev/null || { deactivate; fail "Couldn't update pip."; }
+echo "done"
 
-# These are the packages that we made submodules.
+echo -n "Installing fuzzing targets..."
 for target in targets/*; do
-    cd $target && make && cd ../.. || { deactivate; fail "Couldn't install local package $target."; }
+    cd $target && make &>/dev/null && cd ../.. || { deactivate; fail "Couldn't install local package $target."; }
 done
+echo "done"
 
-# These are the packages that we can just get from pypi
+echo -n "Installing dependencies..."
 for pkg in hypothesis tqdm python-afl black mypy pylint; do
-    pip3 install "$pkg" || { deactivate; fail "Couldn't install remote package $pkg."; }
+    pip3 install "$pkg" &>/dev/null || { deactivate; fail "Couldn't install remote package $pkg."; }
 done
+echo "done"
 
 echo -e "\033[32mYou are now in the fuzzing venv. run \`deactivate\` to exit the venv.\033[0m"
